### ISSUE TITLE
Style Guide for ClassicPress theme

### ISSUE THREAD

**Issue by striebwj** [ClassicPress/ClassicPress-Themes#1]
[ClassicPress-newday2.pdf](https://github.com/ClassicPress/ClassicPress-Themes/files/2543914/ClassicPress-newday2.pdf)
[ClassicPress-styles.pdf](https://github.com/ClassicPress/ClassicPress-Themes/files/2543915/ClassicPress-styles.pdf)
[design-draft.pdf](https://github.com/ClassicPress/ClassicPress-Themes/files/2544140/design-draft.pdf)

**Comment by striebwj** [comment]
In styles document, #231f20 should be #006b81

**Comment by nylen** [comment]
Updated version: [ClassicPress-styles-rev.pdf](https://github.com/ClassicPress/ClassicPress-Themes/files/2545633/ClassicPress-styles-rev.pdf)

**Comment by nylen** [comment]
And [ClassicPress-final-comp.pdf](https://github.com/ClassicPress/ClassicPress-Themes/files/2545634/ClassicPress-final-comp.pdf) too.

**Comment by nylen** [comment]
Closing, let's move this to https://github.com/ClassicPress/ClassicPress-Network/issues if anything specific is still needed.
