### ISSUE TITLE
Search function fixes

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress-Themes#16]
For the inline search function inside the menu I am seeing the following behavior:

- Search for "Docs"
- JavaScript alert appears and says "no results"
- I click OK, and the menu closes.  I've now lost the focus of my current task.

Instead of showing a JavaScript alert, this should show a "no results" message in the same space where search results appear:

![2018-11-11t23 19 52-05 00](https://user-images.githubusercontent.com/227022/48326640-64332380-e608-11e8-95dd-43957e8014c8.png)

Alternatively:  why do we need the search function at all?

cc @KTS915 @striebwj

**Comment by KTS915** [comment]
We definitely need a search function. My usual way of handling this is actually to hijack the browser's alert function with a modal instead, where I can control the focus. But I assumed @nylen wouldn't like that! So I left it as a browser alert.

I will take a look at how to make "No results" (maybe "No matches found") appear somewhere more convenient.

**Comment by KTS915** [comment]
Here's the fix. I'll upload the new `search.js` file. Then you need to add the following CSS to `style.css` at the bottom of the `/* AUTOCOMPLETE */` section:
`.live-search-error {
	z-index: 101;
	padding: 0 0.5em;
	background: #fff;
}`

This CSS will then be compatible with the revised CSS for the menu more generally.

[search.js.zip](https://github.com/ClassicPress/ClassicPress-Themes/files/2572572/search.js.zip)

**Comment by nylen** [comment]
Fixed along with other changes in c3facf9.
