### ISSUE TITLE
Menu drop-down indicator misaligned when hovered

### ISSUE THREAD

**Issue by johnalarcon** [ClassicPress/ClassicPress-Themes#19]
Hovering the About item in the top menu (at ClassicPress.net) causes the indicator to become misaligned. Desktop version. Same in Firefox and Chrome.

![2018-11-12 04_50_19](https://user-images.githubusercontent.com/12477319/48348606-b12dee80-e636-11e8-92b3-3cc6fca2ebbe.jpg)

**Comment by johnalarcon** [comment]
I noticed just now that the drop-down menu also has a gradient background. Just a bit of inconsistency; the mobile version has a solid background.

**Comment by KTS915** [comment]
Yes, I have a fix to make the background solid. Just working on a few other things to make sure everything works together.

**Comment by nylen** [comment]
This seems fixed to me with Tim's latest changes (commit c3facf9); please re-open if you're still seeing it on https://test.classicpress.net/.

**Comment by nylen** [comment]
Ah - I see now, this was an issue with the existing site at www.classicpress.net.

This repository is being used for the new version under development, now visible at https://test.classicpress.net/.

I've fixed it there in the existing site's custom CSS, which will go away after we deploy the new theme.
