### ISSUE TITLE
Another TK Theme Build

### ISSUE THREAD

**Issue by KTS915** [ClassicPress/ClassicPress-Themes#20]
This version attempts to address all the issues raised so far about hover and focus effects, height of menu items, closing menu button on mobile, live search, and the background color of submenus. I also added a class to detect when javascript is active, so that the menu will work even when it is not (though there will be no search available as that requires jQuery to be loaded to add it to the menu).

I remembered to update the cache buster, so the menus and live search should work as intended.

In addition, the six Feature Title boxes have been rebuilt and laid out using CSS Grid instead of flexbox. This never looked right to me when I received it and, having compared it to Michelle's design, I realized that the checkbox images were all missing too.

One other note: I have added icons for Facebook and LinkedIn. Their branding assets do not include circular backgrounds, and I thought it looked very odd to have two square and two round, so I have switched Twitter's to square, but left the round one in the images folder in case you want to change it back. (Github's branding assets do not include a square one.)

As I mentioned, I won't be available for the best part of a week, so I will now just leave you to it!

[classicpress-susty-child-tk4.zip](https://github.com/ClassicPress/ClassicPress-Themes/files/2573936/classicpress-susty-child-tk4.zip)

**Comment by nylen** [comment]
Committed in c3facf9 and uploaded to test.classicpress.net.  Thank you!
