### ISSUE TITLE
Issue reported by W3C Validator

### ISSUE THREAD

**Issue by Mte90** [ClassicPress/ClassicPress-Themes#23]
Just to have more references https://validator.w3.org/nu/?doc=https%3A%2F%2Ftest.classicpress.net%2F

That report that a tag is not closed right.

**Comment by nylen** [comment]
Good find, it looks like this has some major structural issues at the moment.  We can definitely leave the `<script type="">` attributes in place, and the language warning will fix itself when we have some real content, but the rest of that should probably be fixed.  Here's a summary:

![2019-02-01t20 02 41-05 00](https://user-images.githubusercontent.com/227022/52157354-64b5e600-265c-11e9-92dc-ed6d01d75fc0.png)

**Comment by nylen** [comment]
Moving to https://github.com/ClassicPress/ClassicPress-Network/issues/34.
